name: FastAPI CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@4
    
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker Image
      run: |
        docker build -t fastapi-app-test .
    
    - name: Run Tests
      run: |
      # If you have testing framwork like pytest set up, run it here.
      # docker run fastapi-app-test pytest

      
      docker run -d -p 8000:8000 --name test-container fastapi-app-test
      sleep 3
      curl --fail http://localhost:8000/ || exit 1